### ISSUE TITLE
DataParallel NCCL error

### ISSUE THREAD

**Issue by paxcema** [mindsdb/lightwood#332]
* Lightwood version: 0.50.0
* Using 2 RTX 3090 GPUs

Model training fails with a `NCCL Error 2: unhandled system error `. Full stack trace:

```python
File "/home/mindsdb/MindsDB/mindsdb_native/mindsdb_native/libs/phases/model_interface/lightwood_backend.py", line 385, in train
    self.predictor.learn(                                                                                                                                                                                                                                                          
  File "/home/mindsdb/env/lib/python3.8/site-packages/lightwood/api/predictor.py", line 136, in learn         
    self._mixer.fit(train_ds=train_ds, test_ds=test_ds)                                                                                                                                                                                                                            
  File "/home/mindsdb/env/lib/python3.8/site-packages/lightwood/mixers/base_mixer.py", line 51, in fit                                                                                                                                                                             
    self._fit(train_ds, test_ds, **kwargs)                                                                                                                                                                                                                                         
  File "/home/mindsdb/env/lib/python3.8/site-packages/lightwood/mixers/nn.py", line 273, in _fit                                                                                                                                                                                   
    for epoch, training_error in enumerate(self._iter_fit(subset_train_ds, subset_id=subset_id)):                                                                                                                                                                                  
  File "/home/mindsdb/env/lib/python3.8/site-packages/lightwood/mixers/nn.py", line 641, in _iter_fit                                                                                                                                                                              
    outputs = self.net(inputs)                                                                                                                                                                                                                                                     
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                                                                                                         
    result = self.forward(*input, **kwargs)                                                                                                                                                                                                                                        
  File "/home/mindsdb/env/lib/python3.8/site-packages/lightwood/mixers/helpers/default_net.py", line 124, in forward                                                                                                                                                               
    output = self._foward_net(input)                                                                                                                                                                                                                                               
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl                                                                                                                                                                         
    result = self.forward(*input, **kwargs)                                                                                                                                                                                                                                        
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 160, in forward                                                                                                                                                                    
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])                                                                                                                                                                                                          
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in replicate                                                                                                                                                                  
    return replicate(module, device_ids, not torch.is_grad_enabled())                                                                                                                                                                                                              
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 88, in replicate                                                                                                                                                                       
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)                                                                                                                                                                                                           
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape                                                                                                                                                    
    tensor_copies = Broadcast.apply(devices, *tensors)                                                                                                                                                                                                                             
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 22, in forward                                                                                                                                                                        
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)                                                                                                                                                                                                                    
  File "/home/mindsdb/env/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 56, in broadcast_coalesced                        
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)                                                                                                                                                                                                            
RuntimeError: NCCL Error 2: unhandled system error          
```

**Comment by paxcema** [comment]
NCCL info dump:

```                                                                                                                                                                                               
78244:78244 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation                                                                                                                                                                                                                                                                                                                                                                                                                                             
78244:78244 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]                                                                                                                                                                                                   
78244:78244 [0] NCCL INFO Using network Socket                                                                                                                                                                                                                               
NCCL version 2.7.8+cuda11.0                                                                                                                                                                                                                                                        
78244:78465 [0] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
78244:78466 [1] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
78244:78465 [0] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
78244:78466 [1] NCCL INFO Call to connect returned Connection timed out, retrying                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                   
78244:78465 [0] include/socket.h:403 NCCL WARN Connect failed : Connection timed out                                                                                                                                                                   
                                                                                                                                                                                                                                                                                   
78244:78466 [1] include/socket.h:403 NCCL WARN Connect failed : Connection timed out                                                                                                                                                                   
78244:78466 [1] NCCL INFO bootstrap.cc:95 -> 2                                                                                                                                                                                                                               
78244:78466 [1] NCCL INFO bootstrap.cc:309 -> 2                                                                                                                                                                                                                              
78244:78466 [1] NCCL INFO init.cc:555 -> 2                                                                                                                                                                                                                                   
78244:78466 [1] NCCL INFO init.cc:840 -> 2                                                                                                                                                                                                                                   
78244:78465 [0] NCCL INFO bootstrap.cc:95 -> 2                                                                                                                                                                                                                               
78244:78466 [1] NCCL INFO group.cc:73 -> 2 [Async thread]                                                                                                                                                                                                                    
78244:78465 [0] NCCL INFO bootstrap.cc:309 -> 2                                                                                                                                                                                                                              
78244:78465 [0] NCCL INFO init.cc:555 -> 2                                                                                                                                                                                                                                   
78244:78465 [0] NCCL INFO init.cc:840 -> 2                                                                                                                                                                                                                                   
78244:78465 [0] NCCL INFO group.cc:73 -> 2 [Async thread]                                                                                                                                                                                                                    
78244:78244 [0] NCCL INFO init.cc:906 -> 2    
```

**Comment by paxcema** [comment]
Just for the sake of reference: https://github.com/pytorch/pytorch/issues/49095

**Comment by George3d6** [comment]
I guess the problem is as follow:

Data Parallel doesn't work on some GPUs, this is to be expected, we need to figure this out and rollback when it happens. But finding an env to replicate will be hard, I guess we can try catch for `RuntimeError` and then grep for `NLC` in the `forward`. Might do that in the lightwood refacotr... but it might also make sense to forget about this an do parallelism exclusively via ray when it comes to doing that, @paxcema @torrmal thoughts on this? DataParallel might be more efficient than anything we can do with ray.

**Comment by George3d6** [comment]
This is now fixed with a try/catch whereupon we fall back to single GPU. Not much else we can do since the bug is on Nividia's side afaict.
